### ISSUE TITLE
Error running ./configure

### ISSUE THREAD

**Issue by hectoralos** [apertium/apertium-eng#36]
I can't install this (or any other) Apertium package after I git-clone them in my computer. I always have the same issue:

```
./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
./configure: line 2323: syntax error near unexpected token `APERTIUM,'
./configure: line 2323: `PKG_CHECK_MODULES(APERTIUM, apertium >= 3.6.0)'
```

I'm working on Ubuntu 20.04.1 LTS.

I have my system updated and upgraded to the last versions.

I guess, the problem has arisen after I upgrade the system to version 20, but I didn't notice it until I had to compile from scratch a packet.

Any help will be really appreciated because it is right now a blocking issue which prevents me from closing new versions of several packages.

**Comment by ftyers** [comment]
The problem was multiple versions of automake/aclocal in `/usr/local/bin`.
